---
version: '2'
services:
    consul:
        container_name: consul
        image: consul:${CONSUL_TAG}
        network_mode: host
        restart: always
        environment:
          CONSUL_LOCAL_CONFIG: '
            {
                "skip_leave_on_interrupt": false, 
                "leave_on_terminate": true
            }'
        command: agent -server -ui -client 0.0.0.0 -bind $IPV4 -datacenter $DATACENTER -bootstrap-expect $CONSUL_SIZE -retry-join-ec2-tag-key Tenant -retry-join-ec2-tag-value $DATACENTER -node-meta server:$TENANT-$TYPE